changesetIgnorePatterns:
  - .github/**
  - .yarn/**

compressionLevel: mixed

enableGlobalCache: true

nodeLinker: pnp

patchFolder: ./.yarn/patches

pnpEnableEsmLoader: true

pnpUnpluggedFolder: ./.yarn/unplugged

preferInteractive: true

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  os:
    - current
    - darwin
    - linux
    - win32

packageExtensions:
  # Probot does not list smee-client as a dependency,
  # so yarn cannot resolve it without an extension
  "probot@*":
    dependencies:
      smee-client: "*" 
